blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/your-repo/issues/new?template=bug_report.md
    about: Report a bug to help us improve
  - name: Feature Request
    url: https://github.com/your-repo/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
  - name: Project Planning
    url: https://github.com/your-repo/issues/new?template=project_planning.md
    about: For project development and planning