on: 
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Specify the PHP version you are using
    - name: Install Composer dependencies
      run: composer install
    - name: Install Laravel PHPCS standards
      run: composer global require "squizlabs/php_codesniffer=*"
    - name: Run PHPCS inspection
      run: ~/.composer/vendor/bin/phpcs --standard=PSR12 app/ # Adjust the path to your Laravel app directory
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "tests,.github"